### ISSUE TITLE
saltos de linha

### ISSUE THREAD

**Issue by pelgrim** [DIDV/didv_daemon#9]
como converteremos saltos de linha?

**Comment by Torugo** [comment]
podemos fazer como nos livros, deixando as celulas remanescentes em branco. Irei consultar com uma amiga que fez editoração se há algo diferente nos livros braile

**Comment by pelgrim** [comment]
Legal. Estou com uma idéia. Mantemos os autos e criamos um método lines que
pode receber um argumento size. Aí ele fornece um array de linhas do
tamanho especificado, completando com 0s, como vc sugeriu. O que acha?
Em 24/01/2015 19:30, "Torugo" notifications@github.com escreveu:
